services:
  nextjs-app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env.local